#!/bin/bash
# Determination - Deterministic rendering environment for white-axe's music
# Copyright (C) 2024 Liu Hao <whiteaxe@tuta.io>
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

set -eEo pipefail
export PATH="/bin:$PATH"

help () {
  >&2 echo ''
  >&2 echo 'determination-export: export a Carla project deterministically as a FLAC file'
  usage
}

usage () {
  >&2 echo ''
  >&2 echo 'Usage: determination-export path [options]'
  >&2 echo '    path                      Path to the .carxp file to export'
  >&2 echo 'Options:'
  >&2 echo '    -h, --help                Show a help message'
  >&2 echo '    -o/--output <path>        Path where the FLAC file should be exported'
  >&2 echo '                              (default: the input path with the file extension replaced with ".flac")'
  >&2 echo '    -s/--start-bar <integer>  Bar number at which to start rendering audio'
  >&2 echo '                              (default: 1)'
  >&2 echo '    --start-beat <integer>    Beat-within-bar at which to start rendering audio'
  >&2 echo '                              (default: 1)'
  >&2 echo '    --start-tick <integer>    Tick-within-beat at which to start rendering audio'
  >&2 echo '                              (default: 0)'
  >&2 echo '    -e/--end-bar <integer>    Bar number at which to stop rendering audio'
  >&2 echo '                              (default: 101)'
  >&2 echo '    --end-beat <integer>      Beat-within-bar at which to stop rendering audio'
  >&2 echo '                              (default: 1)'
  >&2 echo '    --end-tick <integer>      Tick-within-beat at which to stop rendering audio'
  >&2 echo '                              (default: 0)'
  >&2 echo ''
}

input=''
output=''
start_bar='1'
start_beat='1'
start_tick='0'
end_bar='101'
end_beat='1'
end_tick='0'

opts=$(getopt -n determination-export -o ho:s:e: -l help,start-bar:,start-beat:,start-tick:,end-bar:,end-beat:,end-tick: -- "$@")
eval set -- "$opts"
while true; do
  case "$1" in
    -h|--help) help; exit 0 ;;
    --) input="$2"; if [ -n "$input" ]; then input="$(realpath "$2")"; fi; shift; break ;;
    -o|--output) output="$2"; shift ;;
    -s|--start-bar) start_bar="$2"; shift ;;
    --start-beat) start_beat="$2"; shift ;;
    --start-tick) start_tick="$2"; shift ;;
    -e|--end-bar) end_bar="$2"; shift ;;
    --end-beat) end_beat="$2"; shift ;;
    --end-tick) end_tick="$2"; shift ;;
    *) break ;;
  esac
  shift
done

if [ -z "$input" ]; then usage; exit 1; fi
if [ -z "$output" ]; then output="$(dirname "$input")/$(basename "$input" | cut -d . -f 1).flac"; fi

if [ -S /dev/shm/jack_default_0_0 ]; then
  echo -e '\e[91m[determination-export] Please shut down the JACK server before running this command\e[0m'
  exit 1
fi

echo '[determination-export] Starting up FLAC'
if [ ! -p /determination-renderer-pipe ]; then mkfifo /determination-renderer-pipe; fi
flac --force --fast --force-raw-format --endian=little --channels=2 --bps=24 --sample-rate=48000 --sign=signed -o "$output" - < /determination-renderer-pipe &

echo '[determination-export] Starting up JACK'
jackd -r -d dummy -C 0 -P 0 -r 48000 -p 1024 &
jack_pid=$!
until [ -S /dev/shm/jack_default_0_0 ]; do sleep 0.1; done
sleep 0.5

if LV2_PATH=/lib/lv2 .determination-renderer "$input" "$start_bar" "$start_beat" "$start_tick" "$end_bar" "$end_beat" "$end_tick"; then
  echo '[determination-export] Shutting down JACK'
  kill -INT -$jack_pid

  echo '[determination-export] Canonicalizing'
  flac --force -8 --no-padding --no-seektable "$output"
  metaflac --remove-all --dont-use-padding "$output"
  metaflac --add-seekpoint=10s --dont-use-padding "$output"

  while [ -S /dev/shm/jack_default_0_0 ]; do sleep 0.1; done
  sleep 0.5
  echo '[determination-export] Export finished!'
else
  echo '[determination-export] Shutting down JACK'
  kill -INT -$jack_pid
  while [ -S /dev/shm/jack_default_0_0 ]; do sleep 0.1; done
  sleep 0.5
  echo -e '\e[91m[determination-export] Export failed\e[0m'
fi
