#!/bin/bash
# Determination - Deterministic rendering environment for white-axe's music
# Copyright (C) 2024 Liu Hao <whiteaxe@tuta.io>
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

set -eEo pipefail

export PATH="/bin:$PATH"
export LV2_PATH="/lib/lv2:$LV2_PATH"
export JACK_DEFAULT_SERVER='determination'

help () {
  >&2 echo ''
  >&2 echo 'determination-export: export a Carla project deterministically as a FLAC file.'
  >&2 echo ''
  >&2 echo 'The Carla project should be a Carla patchbay project. This program will record'
  >&2 echo 'whatever audio is passed to the "Audio Output" node in the project. You must'
  >&2 echo 'specify when to start and end recording, as there is no way to automatically'
  >&2 echo 'determine the length of the project.'
  >&2 echo ''
  >&2 echo 'The audio buffer size used for rendering defaults to 1. You may wish to increase'
  >&2 echo 'the buffer size to something like 256 for testing purposes if rendering takes'
  >&2 echo 'too long, but this will change the rendered audio slightly.'
  >&2 echo ''
  >&2 echo 'Aside from Carla internal plugins, the project must only use the following'
  >&2 echo 'external audio plugins. If any of these external audio plugins are available in'
  >&2 echo 'multiple audio plugin formats, use the LV2 version of the audio plugin.'
  >&2 echo '  * Calf Studio Gear <https://github.com/calf-studio-gear/calf>'
  >&2 echo '  * ZynAddSubFX <https://github.com/zynaddsubfx/zynaddsubfx>'
  >&2 echo ''
  >&2 echo 'Caveats:'
  >&2 echo '  * Program changes are not supported.'
  >&2 echo '  * The audio file plugin is not supported.'
  >&2 echo '  * The FluidSynth plugin from Calf Studio Gear is not supported.'
  usage
}

usage () {
  >&2 echo ''
  >&2 echo 'Usage: determination-export path [options]'
  >&2 echo '    path                      Path to the .carxp file to export'
  >&2 echo 'Options:'
  >&2 echo '    -h/--help                 Show a help message and quit'
  >&2 echo '    -o/--output <path>        Path where the FLAC file should be exported'
  >&2 echo '                              (default: the input path with the file extension replaced with ".flac")'
  >&2 echo '    -s/--start-bar <integer>  Bar number at which to start rendering audio'
  >&2 echo '                              (default: 1)'
  >&2 echo '    --start-beat <integer>    Beat-within-bar at which to start rendering audio'
  >&2 echo '                              (default: 1)'
  >&2 echo '    --start-tick <integer>    Tick-within-beat at which to start rendering audio'
  >&2 echo '                              (default: 0)'
  >&2 echo '    -e/--end-bar <integer>    Bar number at which to stop rendering audio'
  >&2 echo '                              (default: 101)'
  >&2 echo '    --end-beat <integer>      Beat-within-bar at which to stop rendering audio'
  >&2 echo '                              (default: 1)'
  >&2 echo '    --end-tick <integer>      Tick-within-beat at which to stop rendering audio'
  >&2 echo '                              (default: 0)'
  >&2 echo '    -r/--rate <integer>       Audio sample rate in hertz'
  >&2 echo '                              (default: 48000, which is equivalent to 48 kilohertz)'
  >&2 echo '    -b/--buffer <integer>     Audio buffer size in samples'
  >&2 echo '                              (default: 1)'
  >&2 echo '    --log-interval <integer>  Microseconds to wait between displays of the rendering progress'
  >&2 echo '                              (default: 10000000, which is equivalent to 10 seconds)'
  >&2 echo ''
}

input=''
output=''
start_bar='1'
start_beat='1'
start_tick='0'
end_bar='101'
end_beat='1'
end_tick='0'
rate='48000'
buffer='1'
log_interval='10000000'

opts=$(getopt -n determination-export -o ho:s:e:r:b: -l help,output:,start-bar:,start-beat:,start-tick:,end-bar:,end-beat:,end-tick:,rate:,buffer:,log-interval: -- "$@")
eval set -- "$opts"
while true; do
  case "$1" in
    -h|--help) help; exit 0 ;;
    --) input="$2"; if [ -n "$input" ]; then input="$(realpath "$2")"; fi; shift; break ;;
    -o|--output) output="$2"; shift ;;
    -s|--start-bar) start_bar="$2"; shift ;;
    --start-beat) start_beat="$2"; shift ;;
    --start-tick) start_tick="$2"; shift ;;
    -e|--end-bar) end_bar="$2"; shift ;;
    --end-beat) end_beat="$2"; shift ;;
    --end-tick) end_tick="$2"; shift ;;
    -r|--rate) rate="$2"; shift ;;
    -b|--buffer) buffer="$2"; shift ;;
    --log-interval) log_interval="$2"; shift ;;
    *) break ;;
  esac
  shift
done

if [ -z "$input" ]; then usage; exit 1; fi
if [ -z "$output" ]; then output="$(dirname "$input")/$(basename "$input" | cut -d . -f 1).flac"; fi

if [ -S "/dev/shm/jack_${JACK_DEFAULT_SERVER}_0_0" ]; then
  >&2 echo -e '\e[91m[determination-export] Please shut down the JACK server before running this command\e[0m'
  exit 1
fi

>&2 echo '[determination-export] Starting up FLAC'
if [ ! -p /.determination-renderer-pipe ]; then mkfifo /.determination-renderer-pipe; fi
flac --force --force-raw-format --endian=little --channels=2 --bps=24 --sample-rate="$rate" --sign=signed -o "$output" - < /.determination-renderer-pipe &

>&2 echo '[determination-export] Starting up JACK'
jackd -r -m -n "$JACK_DEFAULT_SERVER" -p 4096 -S -s -d dummy -C 0 -P 0 -r "$rate" -p "$buffer" &
jack_pid=$!
until [ -S "/dev/shm/jack_${JACK_DEFAULT_SERVER}_0_0" ]; do sleep 0.1; done
sleep 0.5

if .determination-renderer "$input" "$start_bar" "$start_beat" "$start_tick" "$end_bar" "$end_beat" "$end_tick" "$log_interval"; then
  >&2 echo '[determination-export] Shutting down JACK'
  kill -INT -$jack_pid

  >&2 echo '[determination-export] Canonicalizing'
  flac --force -8 --no-padding --no-seektable "$output"
  metaflac --remove-all --dont-use-padding "$output"
  metaflac --add-seekpoint=10s --dont-use-padding "$output"

  while [ -S "/dev/shm/jack_${JACK_DEFAULT_SERVER}_0_0" ]; do sleep 0.1; done
  sleep 0.5
  >&2 echo '[determination-export] Export finished!'
else
  >&2 echo '[determination-export] Shutting down JACK'
  kill -INT -$jack_pid
  while [ -S "/dev/shm/jack_${JACK_DEFAULT_SERVER}_0_0" ]; do sleep 0.1; done
  sleep 0.5
  >&2 echo -e '\e[91m[determination-export] Export failed\e[0m'
fi
