#!/bin/bash
# Determination - Deterministic rendering environment for white-axe's music
# Copyright (C) 2024 Liu Hao <whiteaxe@tuta.io>
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

set -eEo pipefail

export PATH="/bin:$PATH"
export LV2_PATH="/lib/lv2:$LV2_PATH"
export JACK_DEFAULT_SERVER='determination'
export FAUST_OPT='FAUST_LLVM_NO_FM'

help () {
  >&2 echo ''
  >&2 echo 'determination-export: export a Carla project deterministically as a FLAC file.'
  >&2 echo ''
  >&2 echo 'The Carla project should be a Carla patchbay project. This program will record'
  >&2 echo 'whatever audio is passed to the "Audio Output" node in the project. You must'
  >&2 echo 'specify when to start and end recording, as there is no way to automatically'
  >&2 echo 'determine the length of the project.'
  >&2 echo ''
  >&2 echo 'Aside from Carla internal plugins, the project must only use the following'
  >&2 echo 'external audio plugins. If any of these external audio plugins are available in'
  >&2 echo 'multiple audio plugin formats, use the LV2 version of the audio plugin.'
  >&2 echo '  * Mephisto <https://git.open-music-kontrollers.ch/~hp/mephisto.lv2>'
  >&2 echo '  * Moony <https://git.open-music-kontrollers.ch/~hp/moony.lv2>'
  >&2 echo '  * ZynAddSubFX <https://github.com/zynaddsubfx/zynaddsubfx>'
  >&2 echo ''
  >&2 echo 'Caveats:'
  >&2 echo '  * Program changes are not supported.'
  >&2 echo '  * The audio file plugin is not supported.'
  usage
}

usage () {
  >&2 echo ''
  >&2 echo 'Usage: determination-export path [options]'
  >&2 echo '    path                      Path to the .carxp file to export'
  >&2 echo 'Options:'
  >&2 echo '    -h/--help                 Show a help message and quit'
  >&2 echo '    -o/--output <path>        Path where the FLAC file should be exported'
  >&2 echo '                              (default: the input path with the file extension replaced with ".flac")'
  >&2 echo '    -s/--start <integer>      Sample number (the first sample is sample 0) at which to start rendering'
  >&2 echo '                              (default: 0)'
  >&2 echo '    -e/--end <integer>        Sample number (the first sample is sample 0) at which to stop rendering'
  >&2 echo '                              (default: 28800000)'
  >&2 echo '    -r/--rate <integer>       Audio sample rate in hertz (samples per second)'
  >&2 echo '                              (default: 48000, which is equivalent to 48 kilohertz)'
  >&2 echo '    -b/--buffer <integer>     Audio buffer size in samples'
  >&2 echo '                              (default: 128)'
  >&2 echo '    --log-interval <integer>  Microseconds to wait between displays of the rendering progress'
  >&2 echo '                              (default: 10000000, which is equivalent to 10 seconds)'
  >&2 echo ''
}

input=''
output=''
start='0'
end='28800000'
rate='48000'
buffer='128'
log_interval='10000000'

opts=$(getopt -n determination-export -o ho:s:e:r:b: -l help,output:,start:,end:,rate:,buffer:,log-interval: -- "$@")
eval set -- "$opts"
while true; do
  case "$1" in
    -h|--help) help; exit 0 ;;
    --) input="$2"; if [ -n "$input" ]; then input="$(realpath "$2")"; fi; shift; break ;;
    -o|--output) output="$2"; shift ;;
    -s|--start) start="$2"; shift ;;
    -e|--end) end="$2"; shift ;;
    -r|--rate) rate="$2"; shift ;;
    -b|--buffer) buffer="$2"; shift ;;
    --log-interval) log_interval="$2"; shift ;;
    *) break ;;
  esac
  shift
done

if [ -z "$input" ]; then usage; exit 1; fi
if [ -z "$output" ]; then output="$(dirname "$input")/$(basename "$input" | cut -d . -f 1).flac"; fi

if [ -S "/dev/shm/jack_${JACK_DEFAULT_SERVER}_0_0" ]; then
  >&2 echo -e '\e[91m[determination-export] Please shut down the JACK server before running this command\e[0m'
  exit 1
fi

>&2 echo '[determination-export] Starting up FLAC'
if [ ! -p /.determination-renderer-pipe ]; then mkfifo /.determination-renderer-pipe; fi
flac --force --force-raw-format --endian=little --channels=2 --bps=24 --sample-rate="$rate" --sign=signed -o "$output" - < /.determination-renderer-pipe &

>&2 echo '[determination-export] Starting up JACK'
jackd -r -m -n "$JACK_DEFAULT_SERVER" -p 4096 -S -s -d dummy -C 0 -P 0 -r "$rate" -p "$buffer" &
jack_pid=$!
until [ -S "/dev/shm/jack_${JACK_DEFAULT_SERVER}_0_0" ]; do sleep 0.1; done
sleep 0.5

if .determination-renderer "$input" "$start" "$end" "$log_interval"; then
  >&2 echo '[determination-export] Shutting down JACK'
  kill -INT -$jack_pid

  >&2 echo '[determination-export] Canonicalizing'
  flac --force -8 --no-padding --no-seektable "$output"
  metaflac --remove-all --dont-use-padding "$output"
  metaflac --add-seekpoint=10s --dont-use-padding "$output"

  while [ -S "/dev/shm/jack_${JACK_DEFAULT_SERVER}_0_0" ]; do sleep 0.1; done
  sleep 0.5
  >&2 echo '[determination-export] Export finished!'
else
  >&2 echo '[determination-export] Shutting down JACK'
  kill -INT -$jack_pid
  while [ -S "/dev/shm/jack_${JACK_DEFAULT_SERVER}_0_0" ]; do sleep 0.1; done
  sleep 0.5
  >&2 echo -e '\e[91m[determination-export] Export failed\e[0m'
fi
