name: Check
on:
  push:
  pull_request:
  release:
    types:
      - published
  workflow_dispatch:
permissions:
  contents: read
jobs:
  check:
    name: nix flake check
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v27
      - run: nix flake check
  fmt:
    name: nix fmt
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v27
      - run: nix fmt
      - name: Verify that committed code was correctly formatted
        run: |
          git status
          if [[ $(git status --porcelain) ]]; then
            git diff
            echo -e "::error title=nix fmt::Your code is not formatted correctly; please run \`nix --experimental-features 'nix-command flakes' fmt\`"
            exit 1
          fi
